openapi: 3.0.1
info:
  title: Andreuapp
  version: v0
  contact:
    email: a@a.ru
    name: John Doe
servers:
  - url: 'http://localhost:8080'
    description: localhost
paths:
  /v1/groups:
    get:
      summary: Метод отображения всех групп
      tags:
        - Groups
      operationId: findAllGroups
      responses:
        '200':
          description: Успешный ответ со списком групп
          content:
            application/json:
components:
  schemas:

    GroupReadDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        number:
          type: string
        students:
          type: array
          items:
            $ref: '#/components/schemas/StudentReadDto'

    StudentReadDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        fullName:
          type: string
        dateOfEnrollment:
          type: string
          format: date
      StudentUpdateGroupDto:
        type: object
        properties:
          id:
            type: integer
            format: int64
          number:
            type: string


